# Generated by Django 5.0.7 on 2026-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('hash_pw', models.TextField()),
                ('rol', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
