import re, io
text=io.open(r"api/service/views.py",'rb').read().decode('utf-8','ignore')
classes=set(re.findall(r"\nclass\s+(\w+)\s*\(", text))
funcs=set(re.findall(r"\ndef\s+(\w+)\s*\(", text))
print('TOTAL_CLASSES',len(classes))
print('TOTAL_FUNCS',len(funcs))
print('HAS MisPendientesView?', 'MisPendientesView' in classes)
print('HAS QuoteDetailView?', 'QuoteDetailView' in classes)
print('HAS CatalogoTecnicosView?', 'CatalogoTecnicosView' in classes)
print('HAS MetricasResumenView?', 'MetricasResumenView' in classes)
print('HAS ping?', 'ping' in funcs)
