INSERT INTO users (nombre,email,hash_pw,rol,activo,creado_en) VALUES
('EDUARDO','legacy+tecnico1@sepid.com.ar',NULL,'tecnico',1,CURRENT_TIMESTAMP),
('TOMAS','legacy+tecnico2@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('DAMIAN','legacy+tecnico3@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('PATO','legacy+tecnico4@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('JORGE AGUSTIN','legacy+tecnico6@sepid.com.ar',NULL,'tecnico',1,CURRENT_TIMESTAMP),
('LUCAS IGUAL','legacy+tecnico7@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('TECNICO EXTERNO','legacy+tecnico8@sepid.com.ar',NULL,'tecnico',1,CURRENT_TIMESTAMP),
('FLORENCIA','legacy+tecnico9@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('EZEQUIEL','legacy+tecnico10@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('LUIS','legacy+tecnico11@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('BRIAN','legacy+tecnico13@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('EMIR','legacy+tecnico14@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('FRANCO','legacy+tecnico15@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('JOEL','legacy+tecnico17@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('MARTIN','legacy+tecnico18@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('YAMILA','legacy+tecnico19@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('VALENTIN','legacy+tecnico21@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP),
('EZEQUIEL STEMKE','legacy+tecnico24@sepid.com.ar',NULL,'tecnico',0,CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), rol='tecnico', activo=VALUES(activo);
