"""Views export for retail-only cutover."""

from .auth_views import (
    ping,
    LoginView,
    LogoutView,
    SessionView,
    ForgotPasswordView,
    ResetPasswordView,
)

from .usuarios_views import (
    UsuariosView,
    UsuarioActivoView,
    UsuarioResetPassView,
    UsuarioRolePermView,
    UsuarioDeleteView,
    CatalogoPermisosView,
    UsuarioPermisosView,
    UsuarioPermisosResetView,
)

from .retail_views import (
    RetailProductosView,
    RetailProductoDetailView,
    RetailProductoImagenView,
    RetailAtributosView,
    RetailVariantesView,
    RetailVarianteDetailView,
    RetailVarianteEscanearView,
    RetailComprasView,
    RetailCompraDetailView,
    RetailCajaAperturaView,
    RetailCajaCierreView,
    RetailCajaActualView,
    RetailCajaDetailView,
    RetailCajaCuentasView,
    RetailVentasView,
    RetailVentaDetailView,
    RetailGarantiaTicketView,
    RetailGarantiasActivasView,
    RetailVentasCotizarView,
    RetailVentasConfirmarView,
    RetailVentaAnularView,
    RetailVentaDevolverView,
    RetailFacturacionEmitirView,
    RetailFacturacionDetailView,
    RetailFacturacionNotaCreditoView,
    RetailConfigSettingsView,
    RetailConfigPageSettingsView,
    RetailConfigPaymentAccountsView,
    RetailOnlineSyncCatalogoView,
    RetailOnlineSyncStockView,
    RetailOnlineWebhookOrdenPagadaView,
    RetailOnlineWebhookOrdenCanceladaView,
    RetailReporteMasVendidosView,
    RetailReporteTallesColoresView,
    RetailReporteBajoStockView,
    RetailReporteRentabilidadView,
    RetailReporteVentasPorMedioView,
    RetailReporteCierreCajaView,
    RetailReporteDevolucionesView,
)

__all__ = [
    'ping',
    'LoginView',
    'LogoutView',
    'SessionView',
    'ForgotPasswordView',
    'ResetPasswordView',
    'UsuariosView',
    'UsuarioActivoView',
    'UsuarioResetPassView',
    'UsuarioRolePermView',
    'UsuarioDeleteView',
    'CatalogoPermisosView',
    'UsuarioPermisosView',
    'UsuarioPermisosResetView',
    'RetailProductosView',
    'RetailProductoDetailView',
    'RetailProductoImagenView',
    'RetailAtributosView',
    'RetailVariantesView',
    'RetailVarianteDetailView',
    'RetailVarianteEscanearView',
    'RetailComprasView',
    'RetailCompraDetailView',
    'RetailCajaAperturaView',
    'RetailCajaCierreView',
    'RetailCajaActualView',
    'RetailCajaDetailView',
    'RetailCajaCuentasView',
    'RetailVentasView',
    'RetailVentaDetailView',
    'RetailGarantiaTicketView',
    'RetailGarantiasActivasView',
    'RetailVentasCotizarView',
    'RetailVentasConfirmarView',
    'RetailVentaAnularView',
    'RetailVentaDevolverView',
    'RetailFacturacionEmitirView',
    'RetailFacturacionDetailView',
    'RetailFacturacionNotaCreditoView',
    'RetailConfigSettingsView',
    'RetailConfigPageSettingsView',
    'RetailConfigPaymentAccountsView',
    'RetailOnlineSyncCatalogoView',
    'RetailOnlineSyncStockView',
    'RetailOnlineWebhookOrdenPagadaView',
    'RetailOnlineWebhookOrdenCanceladaView',
    'RetailReporteMasVendidosView',
    'RetailReporteTallesColoresView',
    'RetailReporteBajoStockView',
    'RetailReporteRentabilidadView',
    'RetailReporteVentasPorMedioView',
    'RetailReporteCierreCajaView',
    'RetailReporteDevolucionesView',
]



