from django.urls import path

from .views import (
    ForgotPasswordView,
    LoginView,
    LogoutView,
    SessionView,
    ResetPasswordView,
    ping,
    csrf,
    UsuariosView,
    UsuarioActivoView,
    UsuarioResetPassView,
    UsuarioRolePermView,
    UsuarioDeleteView,
    CatalogoPermisosView,
    UsuarioPermisosView,
    UsuarioPermisosResetView,
    RetailProductosView,
    RetailProductoDetailView,
    RetailProductoImagenView,
    RetailAtributosView,
    RetailVariantesView,
    RetailVarianteDetailView,
    RetailVarianteEscanearView,
    RetailVarianteBarcodesView,
    RetailVarianteBarcodeGenerateView,
    RetailVarianteBarcodeAssociateView,
    RetailVarianteBarcodePrimaryView,
    RetailVarianteBarcodeLabelsPdfView,
    RetailComprasConfigView,
    RetailComprasProveedoresView,
    RetailComprasView,
    RetailCompraDetailView,
    RetailCajaAperturaView,
    RetailCajaCierreView,
    RetailCajaActualView,
    RetailCajaDetailView,
    RetailCajaCuentasView,
    RetailVentasView,
    RetailVentaDetailView,
    RetailPromocionesView,
    RetailPromocionDetailView,
    RetailGarantiaTicketView,
    RetailGarantiasActivasView,
    RetailVentasCotizarView,
    RetailVentasConfirmarView,
    RetailPosDraftsView,
    RetailPosDraftDetailView,
    RetailPosDraftConfirmView,
    RetailVentaAnularView,
    RetailVentaDevolverView,
    RetailVentaCambiarView,
    RetailFacturacionEmitirView,
    RetailFacturacionDetailView,
    RetailFacturacionNotaCreditoView,
    RetailConfigSettingsView,
    RetailConfigPageSettingsView,
    RetailConfigPaymentAccountsView,
    RetailOnlineSyncCatalogoView,
    RetailOnlineSyncStockView,
    RetailOnlineWebhookOrdenPagadaView,
    RetailOnlineWebhookOrdenCanceladaView,
    RetailOnlineWebhookStoreRedactView,
    RetailReporteResumenComercialView,
    RetailReporteAnalisisProductosView,
    RetailReporteAnalisisProveedoresView,
    RetailReporteMasVendidosView,
    RetailReporteTallesColoresView,
    RetailReporteBajoStockView,
    RetailReporteRentabilidadView,
    RetailReporteVentasPorMedioView,
    RetailReporteCierreCajaView,
    RetailReporteDevolucionesView,
)

urlpatterns = [
    path('ping/', ping),
    path('auth/csrf/', csrf),
    path('auth/login/', LoginView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/session/', SessionView.as_view()),
    path('auth/forgot/', ForgotPasswordView.as_view()),
    path('auth/reset/', ResetPasswordView.as_view()),

    path('usuarios/', UsuariosView.as_view()),
    path('usuarios/<int:uid>/activar/', UsuarioActivoView.as_view()),
    path('usuarios/<int:uid>/reset-pass/', UsuarioResetPassView.as_view()),
    path('usuarios/<int:uid>/roleperm/', UsuarioRolePermView.as_view()),
    path('usuarios/<int:uid>/', UsuarioDeleteView.as_view()),
    path('permisos/catalogo/', CatalogoPermisosView.as_view()),
    path('usuarios/<int:uid>/permisos/', UsuarioPermisosView.as_view()),
    path('usuarios/<int:uid>/permisos/reset/', UsuarioPermisosResetView.as_view()),

    path('retail/productos/', RetailProductosView.as_view()),
    path('retail/productos/<int:producto_id>/', RetailProductoDetailView.as_view()),
    path('retail/productos/<int:producto_id>/imagen/', RetailProductoImagenView.as_view()),
    path('retail/atributos/', RetailAtributosView.as_view()),
    path('retail/variantes/', RetailVariantesView.as_view()),
    path('retail/variantes/<int:variante_id>/', RetailVarianteDetailView.as_view()),
    path('retail/variantes/escanear/<str:codigo>/', RetailVarianteEscanearView.as_view()),
    path('retail/variantes/<int:variante_id>/barcodes/', RetailVarianteBarcodesView.as_view()),
    path('retail/variantes/<int:variante_id>/barcodes/generate/', RetailVarianteBarcodeGenerateView.as_view()),
    path('retail/variantes/<int:variante_id>/barcodes/associate/', RetailVarianteBarcodeAssociateView.as_view()),
    path('retail/variantes/<int:variante_id>/barcodes/primary/', RetailVarianteBarcodePrimaryView.as_view()),
    path('retail/variantes/<int:variante_id>/barcodes/labels.pdf', RetailVarianteBarcodeLabelsPdfView.as_view()),

    path('retail/compras/config/', RetailComprasConfigView.as_view()),
    path('retail/compras/proveedores/', RetailComprasProveedoresView.as_view()),
    path('retail/compras/', RetailComprasView.as_view()),
    path('retail/compras/<int:compra_id>/', RetailCompraDetailView.as_view()),

    path('retail/caja/apertura/', RetailCajaAperturaView.as_view()),
    path('retail/caja/cierre/', RetailCajaCierreView.as_view()),
    path('retail/caja/actual/', RetailCajaActualView.as_view()),
    path('retail/caja/cuentas/', RetailCajaCuentasView.as_view()),
    path('retail/caja/<int:caja_id>/', RetailCajaDetailView.as_view()),

    path('retail/ventas/', RetailVentasView.as_view()),
    path('retail/ventas/<int:venta_id>/', RetailVentaDetailView.as_view()),
    path('retail/promociones/', RetailPromocionesView.as_view()),
    path('retail/promociones/<int:promocion_id>/', RetailPromocionDetailView.as_view()),
    path('retail/ventas/cotizar/', RetailVentasCotizarView.as_view()),
    path('retail/ventas/confirmar/', RetailVentasConfirmarView.as_view()),
    path('retail/pos/drafts/', RetailPosDraftsView.as_view()),
    path('retail/pos/drafts/<int:draft_id>/', RetailPosDraftDetailView.as_view()),
    path('retail/pos/drafts/<int:draft_id>/confirm/', RetailPosDraftConfirmView.as_view()),
    path('retail/ventas/<int:venta_id>/anular/', RetailVentaAnularView.as_view()),
    path('retail/ventas/<int:venta_id>/devolver/', RetailVentaDevolverView.as_view()),
    path('retail/ventas/<int:venta_id>/cambiar/', RetailVentaCambiarView.as_view()),
    path('retail/garantias/ticket/<str:codigo>/', RetailGarantiaTicketView.as_view()),
    path('retail/garantias/activas/', RetailGarantiasActivasView.as_view()),

    path('retail/facturacion/<int:venta_id>/emitir/', RetailFacturacionEmitirView.as_view()),
    path('retail/facturacion/<int:venta_id>/', RetailFacturacionDetailView.as_view()),
    path('retail/facturacion/<int:venta_id>/nota-credito/', RetailFacturacionNotaCreditoView.as_view()),

    path('retail/config/settings/', RetailConfigSettingsView.as_view()),
    path('retail/config/page-settings/', RetailConfigPageSettingsView.as_view()),
    path('retail/config/payment-accounts/', RetailConfigPaymentAccountsView.as_view()),

    path('retail/online/sync/catalogo/', RetailOnlineSyncCatalogoView.as_view()),
    path('retail/online/sync/stock/', RetailOnlineSyncStockView.as_view()),
    path('retail/online/webhooks/orden-pagada/', RetailOnlineWebhookOrdenPagadaView.as_view()),
    path('retail/online/webhooks/orden-cancelada/', RetailOnlineWebhookOrdenCanceladaView.as_view()),
    path('retail/online/webhooks/store-redact/', RetailOnlineWebhookStoreRedactView.as_view()),

    path('retail/reportes/resumen-comercial/', RetailReporteResumenComercialView.as_view()),
    path('retail/reportes/analisis-productos/', RetailReporteAnalisisProductosView.as_view()),
    path('retail/reportes/analisis-proveedores/', RetailReporteAnalisisProveedoresView.as_view()),
    path('retail/reportes/mas-vendidos/', RetailReporteMasVendidosView.as_view()),
    path('retail/reportes/talles-colores/', RetailReporteTallesColoresView.as_view()),
    path('retail/reportes/bajo-stock/', RetailReporteBajoStockView.as_view()),
    path('retail/reportes/rentabilidad/', RetailReporteRentabilidadView.as_view()),
    path('retail/reportes/ventas-por-medio/', RetailReporteVentasPorMedioView.as_view()),
    path('retail/reportes/cierre-caja/', RetailReporteCierreCajaView.as_view()),
    path('retail/reportes/devoluciones/', RetailReporteDevolucionesView.as_view()),
]



