upstream api {
    server api:8000;
    keepalive 16;
}

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Estáticos: cache fuerte
    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # Backend
    location /api/ {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://api;
    }

    # Single Page App
    location / {
        try_files $uri /index.html;
    }

    # uploads, si aplica (ajustar tamaño)
    client_max_body_size 20m;

    # gzip básico
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
