FROM node:20-alpine AS builder
WORKDIR /app

# Dependencies layer
COPY package*.json ./
RUN npm ci

# Build with optional API base passed at build time
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

COPY . .
RUN npm run build

FROM nginx:alpine AS server
WORKDIR /

# Nginx conf for SPA + static
COPY --chown=root:root --from=builder /app/dist /usr/share/nginx/html
COPY --chown=root:root deploy/web.nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

